project/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: [:show]
  resources :products, only: [:show] do
    get :search, on: :collection
  end
  resources :shopping_carts
  resources :addresses do
    member do
      put :set_default_address
    end
  end
  resources :orders
  resources :payments, only: [:index]
  namespace :dashboard do
    scope 'profile' do
      controller :profile do
        get :password
        put :update_password
      end
    end

    resources :orders, only: [:index]
    resources :addresses, only: [:index]
  end

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products
  end
end

project/app/views/admin/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= admin_root_path %>">管理平台</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= admin_categories_path %>">分类</a></li>
        <li><a href="<%= admin_products_path %>">商品</a></li>
        <li><a href="#">欢迎你, <%= current_user.username %></a></li>
        <li><%= link_to "退出", logout_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

project/app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>20373384-e-market-管理平台</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'admin', media: 'all' %>
  <%= yield :stylesheets %>
</head>

<body>
<%= render 'admin/layouts/menu' %>
<div class="container">
  <% unless flash[:notice].blank? %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end -%>

  <%= yield %>
</div>

<%= javascript_include_tag 'admin' %>
<%= yield :javascripts %>
</body>
</html>