project/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: [:show]
  resources :products, only: [:show] do
    get :search, on: :collection
  end
  resources :shopping_carts
  resources :addresses do
    member do
      put :set_default_address
    end
  end
  resources :orders
  resources :payments, only: [:index]
  namespace :dashboard do
    scope 'profile' do
      controller :profile do
        get :password
        put :update_password
      end
    end

    resources :orders, only: [:index]
    resources :addresses, only: [:index]
  end

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products
  end
end

project/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  layout false
  before_action :auth_user
  before_action :find_address, only: [:edit, :update, :destroy, :set_default_address]

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = current_user.addresses.new
  end

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      @addresses = current_user.reload.addresses
      render json: {
        status: 'ok',
        data: render_to_string('addresses/index')
      }
    else
      render json: {
        status: 'error',
        data: render_to_string('addresses/new')
      }
    end
  end

  def edit
    render action: :new
  end

  def update
    @address.attributes = address_params
    if @address.save
      @addresses = current_user.reload.addresses
      render json: {
        status: 'ok',
        data: render_to_string('addresses/index')
      }
    else
      render json: {
        status: 'error',
        data: render_to_string('addresses/new')
      }
    end
  end

  def destroy
    @address.destroy

    @addresses = current_user.addresses
    render json: {
      status: 'ok',
      data: render_to_string('addresses/index')
    }
  end

  def set_default_address
    @address.set_as_default = 1
    @address.save

    @addresses = current_user.reload.addresses
    render json: {
      status: 'ok',
      data: render_to_string('addresses/index')
    }
  end

  private
  def address_params
    params.require(:address).permit(:contact_name, :cellphone, :address,
                                    :zipcode, :set_as_default)
  end

  def find_address
    @address = current_user.addresses.find(params[:id])
  end

end

project/app/controllers/dashboard/addresses_controller.rb
class Dashboard::AddressesController < Dashboard::BaseController

  def index
  end

end

project/app/helpers/dashboard/addresses_helper.rb
module Dashboard::AddressesHelper
end

project/app/views/addresses/index.html.erb
<div class="pull-right">
  <%= link_to "新建收货地址", new_address_path, class: "btn btn-info new-address-btn" %>
</div>
<div class="clearfix"></div>
<br />
<ul class="list-group">
  <% unless @addresses.blank? %>
    <% @addresses.each_with_index do |address, index| %>
      <li class="list-group-item">
        <label>
          <input type="radio" name="address_id" value="<%= address.id %>" <%= 'checked' if current_user.default_address == address %> />
          <%= address.contact_name %>
          <%= address.address %>
          <%= address.cellphone %>

          <%= link_to "编辑", edit_address_path(address), remote: true, class: "inline edit-address-btn" %>
          <%= link_to "删除", address_path(address), remote: true, method: 'delete', "data-confirm": "确认删除该地址吗？", class: "remove-address-btn inline" %>
          <% if current_user.default_address == address %>
            <span class="default_address">默认地址</span>
          <% else %>
            <%= link_to "设为默认收货地址", set_default_address_address_path(address), remote: true, method: 'put', class: "set-default-address-btn inline" %>
          <% end %>
        </label>
      </li>
    <% end %>
  <% else %>
    <li class="list-group-item">
      请添加送货地址
    </li>
  <% end %>
</ul>

project/app/views/addresses/new.html.erb
<div class="modal fade" tabindex="-1" id="address_form_modal">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">收货地址</h2>
      </div>
      <%= form_for @address, url: (@address.new_record? ? addresses_path : address_path(@address)), method: (@address.new_record? ? :post : :put), remote: true, html: { class: "form-horizontal address-form" } do |f|  %>
        <div class="modal-body">
          <% unless @address.errors.blank? %>
            <div class="alert alert-danger">
              <ul>
                <% @address.errors.messages.values.flatten.each do |error| %>
                  <li><%= error %></li>
                <% end -%>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="address" class="col-sm-2 control-label">详细地址:*</label>
            <div class="col-sm-7">
              <%= f.text_area :address, class: "form-control" %>
            </div>
            <div class="col-sm-2 address_input_error">
            </div>
          </div>
          <div class="form-group">
            <label for="contact_name" class="col-sm-2 control-label">姓名:*</label>
            <div class="col-sm-7">
              <%= f.text_field :contact_name, class: "form-control" %>
            </div>
            <div class="col-sm-2 address_input_error">
            </div>
          </div>
          <div class="form-group">
            <label for="cellphone" class="col-sm-2 control-label">手机号码:*</label>
            <div class="col-sm-7">
              <%= f.text_field :cellphone, class: "form-control" %>
            </div>
            <div class="col-sm-2 address_input_error">
            </div>
          </div>
          <div class="form-group">
            <label for="zipcode" class="col-sm-2 control-label">邮政编码:</label>
            <div class="col-sm-7">
              <%= f.text_field :zipcode, class: "form-control" %>
            </div>
            <div class="col-sm-2 address_input_error">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <label>
                <input type="checkbox" name="address[set_as_default]" <%= 'checked' if current_user.default_address == @address %> value="1" /> 设为默认地址
              </label>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
          <span class="address_form_progress"></span>
          <%= f.submit "保存", class: "btn btn-primary" %>
        </div>
      <% end -%>
    </div>
  </div>
</div>